nomunomu0504/covid19

README.md

- close #2 
- `README.md`のヘッダ画像を`/static/ogp.png`(福井県用ヘッダ)に変更

READMEのヘッダ画像を変更

---

components/SideNavigation.vue
pages/japan-news.vue
pages/news.vue

- close #18 
- 福井県内, 国内のお知らせだけを表示する専用のページを作成
- 福井県内
- 国内

福井県内, 国内のお知らせ一覧専用ページを作成

---

pages/index.vue

- #11 
- 一時的にPCR検査実施件数に関するグラフを本番環境から非表示にした

PCR検査実施件数のカードがスマホで正常に動作していないので一時的に非表示処理

---

nuxt-i18n.config.ts

- close #30 
- `nuxt-i18n.config.ts` の `vueI18n` に `silentTranslationWarn: true` を追加
- 環境依存で挙動が変わる可能性があるので、レビュワーは各自開発環境で実行して確認してください。
アクセス時のエラー/警告が `403` のみになった

add silentTranslationWarn

---

components/cards/YoutubeCard.vue
pages/index.vue

- #28 
- YouTube動画を表示しておくカードを一時的に非活性化。臨時記者会見が行われる時に埋め込みリンクを更新することで一時的に対応する。

YouTube API関係が整理できるまでは、常時表示を中止, LIVEの都度更新で臨時対応

---

components/TimeStackedBarChart.vue

日付情報を使用しないようにした
- close #36 
- `components/TimeStackedBarChart.vue`の週別及び類型のsTextの表記を`date`を用いない表記に変更

検査実施人数カードのsTextの表記を変更

---

components/cards/ConfirmedCasesNumberCard.vue

- close #65 
- #57 
- グラフデータは patients_summary.json から、更新日時は patients.json から取得していた
- いずれもdata/patients_summary.jsonから取得するよう変更

陽性患者数カードのデータと更新日時を同じファイルから取得

---

CONTRIBUTORS.md
pages/cards/_card.vue

- #85 
- 陽性患者数に関する単体のグラフが正常に表示されないバグを修正

陽性患者数のグラフが表示されないバグを修正

---

components/BreakingNews.vue
components/FukuiNews.vue
components/FukuiPaperNews.vue
nuxt.config.ts
pages/index.vue

- 感染動向の情報鮮度は福井県の新着情報より福井新聞社の方が良いため、RSSモジュールを追加したい
- close #96 
- RSSフィードの最新3件をトップページで表示
- UIは他のお知らせモジュールと同一
- 一旦リリースし、福井県のRSSフィードを含めてあとでUI改善を行いたい

#96 トップページに福井新聞社のRSSフィードを表示

---

components/ConfirmedCasesTable.vue
utils/formatConfirmedCases.ts

自宅療養と宿泊施設を除去
- #126 
- #134
- 検査陽性者の状況テーブルを修正
- 自宅療養と宿泊施設等をコメントアウト
- 復帰予定で、復帰には #114 を参照

陽性者の状況テーブルを修正

---

components/cards/ConfirmedCasesAttributesCard.vue
components/cards/ConfirmedCasesNumberCard.vue

福井県の新型コロナウイルス オープンデータのページへ変更
- close #150
- #126
- ソースデータのリンク先を福井県 新型コロナウイルスオープンデータのページへ変更

ソースデータのリンクを修正

---

covid19_fukui/csv2json.js

ファイルをUTF-8としてするように
- #126
- #134 
- スクレイピングスクリプトが取得するcsvファイルをUTF-8として処理するように変更
- Shift-JISからの変換をしないようにした

Shift-JIS変換を無効化

---

covid19_fukui/csv2json.js

- #126
- #134
- #161
- スクレイピングスクリプトにコールセンター相談件数のデータをJSONとして生成するように変更

コールセンター相談件数のデータを生成するように変更

---

.github/workflows/push_fukui_data.yml

- #176
- #177
- JSONの更新時、重複するPRを削除するようにしました
- PRの作成に関して、複数のブランチを指定できるようになりました
- 例: `/updatejson nomu_production nomu_development`
- Slackのコマンドの1番目の引数が作成元のブランチに、
- 2番目以降の引数で指定されたブランチは、1番目の引数のブランチが親となります
こんな Pull Request が作成されます→ https://github.com/satackey/covid19-fukui/pull/43

JSONの更新時、重複するPRの削除・複数のブランチの指定機能を追加

---

pages/index.vue

サイドバーにはリンクが残っている
- close #209
- #96 
- トップページから「最新のお知らせ(福井県内)」カードを除去

最新のお知らせ(福井県内)カードをトップページから除去

---

components/BreakingNews.vue
pages/index.vue

- close #224
- 速報カードをお知らせ(県内)カードと同様に3件のデータを表示するように変更
- 速報カードに渡すデータをお知らせ(県内)のデータに変更

速報カードのデータをお知らせからとってくるように変更

---

covid19_fukui/csv2json.js

- close #870
- 日毎の患者数データの生成を、スクリプト実行日から最新陽性患者公表日までに変更

日毎の患者数データの更新を最新データまでで打ち切るよう変更

---

components/TimeBarChart.vue
components/cards/HospitalizedPatientsCard.vue
covid19_fukui/csv2json.js
pages/cards/_card.vue
pages/index.vue
utils/colors.ts

- close #937
- 入院患者数の推移をJSONに生成するようスクリプトを変更
- 入院患者数の推移をグラフとして表示するカードを追加
- 一部lintの対応
- ~~グラフデータがマイナスの場合に赤色にする~~
- 注釈などの文章の調整
- 配置の調整

入院患者数の推移を表示するカードを追加

---

covid19_fukui/csv2json.js

- close #977
- #870
- #871
- 日毎の患者数データをスクレイピングスクリプトを実行した当日分まで生成するように変更

日毎の患者数データを当日分まで生成するよう変更

---

pages/cards/_card.vue

- close #1179 
- 入院患者数カードが単体で呼ばれた時の名前に不一致があったので修正した
- 修正前
- 修正後

入院患者数カードが単体で呼ばれた時の定義を修正

---

pages/index.vue

- close #1149
- 感染症病床使用率カードを陽性患者の属性カードより上に移動

感染症病床使用率カードを移動

---

components/SideNavigation.vue
pages/index.vue

- close #2222
- サイドバーのマスクに関するページへのリンクを解除

マスクに関する情報ページを無効化

---

pages/index.vue

- close #5421
- #4281
- トップページに検査実施人数カードを表示するように変更

検査実施人数カードを復活

---

components/CircleChart.vue

- close #5422
- 病床使用率の円グラフの色を感染状況の評価指標に合うように変更
- それに合わせて注釈を修正

病床使用率の円グラフの色を感染状況の評価指標に合わせて変更

---

components/cards/ConfirmedCasesAttributesCard.vue
utils/formatTable.ts

- close #6435 
- 陽性患者の属性カードから不要な項目を削除
- カードの幅を半分に変更

陽性患者の属性カードから不要な項目を削除

---

components/cards/ConfirmedCasesAttributesCard.vue

- close #7175 
- 陽性患者の属性カードの幅が画面サイズに合わせて調整されるようにした

画面の幅が小さいときに陽性患者の属性カードの表示が小さくなる問題を修正

---

components/HorizontalBarChart.vue

- close #3034
- 年代別の陽性患者数のカードを男女別に分割した
- 男性をマイナス方向に変換
- グラフの色は `utils/colors.ts` の `plusMinus` を利用

年代別の陽性患者数カードを男女別に分割した
