nomunomu0504/covid19

data/data.json

- close #3 
- #4 のブランチ先変更PR
- `data/data.json`の入院中/軽症・中等症の人数を変更
- マージ先ブランチを`nomu_production`へ変更

検査陽性者の状況データを更新

---

components/cards/InspectionPersonsNumberCard.vue

検査実施人数グラフのマウスオーバーに関するバグを修正

---

components/CircleChart.vue
components/cards/HospitalBedsNumberCard.vue
data/data.json
pages/cards/_card.vue
pages/index.vue
plugins/vue-chart.ts
utils/formatVariableGraph.ts

病床数を円グラフで表示させる

---

components/cards/YoutubeCard.vue
package.json
pages/index.vue
yarn.lock

- close #22 
- 福井県のYoutube配信を追加

福井県のYoutube配信を表示するカードを追加

---

CONTRIBUTORS.md

contributorの追加

---

components/cards/YoutubeCard.vue
youtube-card.config.js

- close #28 
- #23 
- Youtube API key を差し替えてください
- youtube-card.config.js に設定を分離したのでそこを書き換えてください

Youtube API key を差し替え

---

CONTRIBUTORS.md

- none
- none
- Fix markdonw table grammer in CONTRIBUTORS.md

Fix markdown table grammer in CONTRIBUTORS.md

---

components/cards/YoutubeCard.vue
covid19_fukui/covid19fukui.js
youtube-card.config.js

- close #43 
- #28 
- #32 
- バックエンド側にYoutubeの動画リストを取得するコードを移しました
- 取得した動画リストは youtubeVideolist.json に保存されます
- Youtube API key と Youtube のユーザー名は環境変数から読むようにしました
- それぞれ YOUTUBE_API_KEY と YOUTUBE_USERNAME としています
- None

Youtube動画リストをバックエンド側で取得させる

---

README.md

【テストPR_development】
- READMEを修正

【テストPR_development】リポジトリのREADME.mdを修正

---

README.md
package.json
pm2.config.js

【テストPR_production】
- READMEを修正

【テストPR_production】リポジトリのREADME.mdを修正

---

README.md

権限確認のためのテストコミット

---

README.md

権限確認のためのテストコミットの修正

---

Dockerfile

- close #58 
- Dockerの実行コマンドを`package.json`内にあるものと対応づけした

Dockerの実行コマンドを修正

---

pages/about.vue

- close #75 
リポジトリへのリンクを修正しました

githubリポジトリのリンク間違いを修正

---

CONTRIBUTORS.md

contributorsを追加

---

components/FukuiNews.vue
nuxt.config.ts
package.json
pages/index.vue
yarn.lock

- close #93
- close #50 
- RSSフィードの最新3件をトップページで表示
- UIは他のお知らせモジュールと同一
- Twitter/Facebookは更新頻度が少ないので、SNSページのissueはcloseする
- asyncDataによるSSRは、実装してみたが、動作しなかったため保留

トップページに福井県のRSSフィードを表示

---

components/FukuiPaperNews.vue

- close #101
- ソースコードのタイポを修正した

#101 福井新聞社のtypo 

---

pages/index.vue

- #103 
- RSSモジュールを下げて、県・国内のお知らせを一時的に復活させる

【hotfix】RSSモジュールを下げる

---

components/DevelopmentModeMark.vue

- close #107 
- 開発モード時に表示されるリンク先を福井県サイトに修正

開発モード時に表示されるリンク先のURLを修正

---

components/CircleChart.vue

- close #111
- 感染症病床使用率カードの注釈中に含まれる資料のリンクを解除
- その他Lintの問題を解決

注釈中のリンクを解除

---

netlify.toml

↓Issueの一部のコメントに対しての改善のため省略
- https://github.com/nomunomu0504/covid19/issues/48#issuecomment-609821558
NetlifyのPRプレビュー時に本番環境と同じ動作をさせるように変更しました。
現在はupdatejsonコマンドを実行したときのみ更新させていて、Netlifyのデプロイ時にはコミットされたデータを使っています。
UI等の変更はないため省略

PRのプレビューはprodunctionの動作で実行

---

components/TimeBarChart.vue
components/TimeStackedBarChart.vue

- close #100 
- moment.js に依存すると思われる部分を削除

moment.jsに関するワーニングの抑制

---

.github/workflows/push_fukui_data.yml
covid19_fukui/.gitignore
covid19_fukui/Dockerfile
docker-compose.yml

※Slackの話のため省略
-  スクレイピングから取得してるデータ以外をスプレッドシートで管理 #48
- python3/build-essentialをjson取得のDocker環境に追加し、iconvのインストールが可能になりました
- Secretsの`CSV_FETCH_ENV`に設定された複数の環境変数をデータ取得のスクリプト実行時に利用可能にしました
※省略

CSV取得の環境整備

---

.github/workflows/push_fukui_data.yml

※Slackの話のため省略
-  スクレイピングから取得してるデータ以外をスプレッドシートで管理 #48
- updatejson コマンドでのブランチ指定機能の追加
- 更新時に常に`update_fukui_data/updatejson`ブランチを使用
※省略

ブランチ指定の機能の追加 & 更新時に常に同じブランチを使用

---

.github/workflows/push_fukui_data.yml

※省略
※省略
- #117 の不具合を修正しました
スクリーンショットではありませんが、 Slackの `/updatejson { head_branch_name }`コマンドで #132 のようなPRがActionsより作成されます

Workflowの間違いを修正

---

covid19_fukui/csv2json.js

- #126
- #134 
- 無症状病原体保有者に対応
- 発症日がない場合は何も入れないように変更

無症状病原体保有者に対応

---

covid19_fukui/csv2json.js

- #126
- #134 
- 検査実施人数をStringからIntに変更

[WIP] 検査実施人数をStringからIntに変更

---

covid19_fukui/csv2json.js

Reverts nomunomu0504/covid19#139

Revert "検査実施人数をStringからIntに変更"

---

covid19_fukui/csv2json.js

Reverts nomunomu0504/covid19#140

Revert "Revert "検査実施人数をStringからIntに変更""

---

components/DataSelector.vue
components/TimeBarChart.vue
components/TimeStackedBarChart.vue
components/cards/ConfirmedCasesNumberCard.vue

- #126 
- #134
- 週別表記だった検査実施人数を日別表記に変更

検査実施人数データの表記を日別に修正

---

covid19_fukui/csv2json.js

- #126 
- #134
- 更新時刻がUTCとなっていたものをJSTに変更

UTC表記の更新時刻をJSTに変更

---

covid19_fukui/package.json

package.jsonを復帰

---

components/TimeBarChart.vue

- close #173 
- TimeBarChartのX軸回転を60まで許容するよう変更

TimeBarChartのX軸ラベルを自動回転

---

covid19_fukui/csv2json.js

- #126 
- #134 
- #160 
- 病床数を環境変数から取得できるように変更
- `HOSPITAL_BEDS`に数値を入れればその値を使います
- 値がない場合はエラー終了します
- 一部でリファクタリングを実施

スクリプトの病床数を環境変数から取り出すように変更

---

components/DateSelectSlider.vue
components/TimeBarChart.vue
plugins/vue-chart.ts

~~## 👏 解決する issue / Resolved Issues~~
- #119 
- TimeBarChartに表示期間を示すスライダーを追加

TimeBarChartにスライダーを追加

---

covid19_fukui/csv2json.js
covid19_fukui/package-lock.json
covid19_fukui/package.json
data/fukuishimbun.json

- close #181
- リンク先の記事に「コロナ」または「感染」の文字列が含まれる記事のみjson化する

リンク先の記事にコロナか感染がある場合だけ抽出

---

components/FukuiPaperNews.vue
components/SideNavigation.vue
netlify.toml
nuxt.config.ts
package-lock.json
package.json
pages/rss-news.vue
store/index.ts

- close #188 
- RSSをAPI経由で取得
- RSS専用ページ作成

RSSをAPIから取得

---

.github/auto-merge-bot.config.yml
.github/workflows/push_fukui_data.yml

- close #190 
- 1時間毎にGitHub Actionsのワークフローを実行・PRを作成
- `nomu_production`を元にブランチを切り、`nomu_production`と`nomu_development`の両方にPRを出します
- 、[auto-merge-bot](https://github.com/apps/auto-merge-bot)より自動でApprove&Mergeされるように設定しました
@nomunomu0504 ↑auto-merge-botのインストールをお願いします

データ更新のPRを自動でMergeする

---

covid19_fukui/csv2json.js

- #126 
- #134 
- 検査陽性者の状況で用いていた条件のミスを修正

検査陽性者の状況の計算に用いた条件を修正

---

README.md

- close #266
- `REAMD.md`の`nomu_development`ブランチの反映先アドレスを変更

nomu_developmentブランチの反映先アドレスを変更

---

covid19_fukui/csv2json.js

陰性確認件数のアドレスから入退院件数へ変更
- close #322
- スクレイピングスクリプトのアクセス先を変更
- 入退院件数を取得するように

アクセス先アドレスを変更

---

covid19_fukui/csv2json.js

- close #360 
* #134 
- オープンデータから取得したデータがすでに保有するデータと異なる場合のみ更新をするように変更
- 一部関数などにJSDocを追加

スクレイピングしたデータが更新されている場合のみ変更する

---

components/BreakingNews.vue

- close #359
- 速報カードに福井県緊急事態宣言へのリンクボタンを追加

緊急事態宣言へのリンクボタンを設置

---

covid19_fukui/csv2json.js

- close #583
- #544
- #547
- timestampを除去するJSONオブジェクトをコピーしたものに変更

timestampをファイルに出力するよう修正

---

.github/workflows/push_fukui_data.yml

- close #584 
- JSONの更新を行った直後に、diffの有無を`'true'`/`'false'`で出力
- 無しの場合はブランチの作成・コミット・プッシュ等を行わずに終了
更新が無い時のActions 実行結果例: https://github.com/satackey/covid19-fukui/runs/599068908

自動JSON更新の変更無し時はコミット等をスキップする

---

covid19_fukui/csv2json.js

データの訂正
- データの誤りを訂正
- データに確認が取れた不足分を追加

オープンデータの不備に対する暫定対応 その2

---

components/cards/ConfirmedCasesAttributesCard.vue
components/cards/ConfirmedCasesDetailsCard.vue
components/cards/ConfirmedCasesNumberCard.vue
components/cards/EachSexAgeNumberPositiveCard.vue
components/cards/HospitalBedsNumberCard.vue
components/cards/InformationNumberCard.vue
components/cards/InspectionPersonsNumberCard.vue
pages/index.vue
utils/formatDate.ts

- close #661 
- ページトップの「最終更新」で最も最近の更新時刻を表示
- 時刻表記を `toLocaleString` に**統一**
- `getCommonStyleDateString` 関数を作成
- `index.vue` で使われていない `data` のプロパティを**削除**
- `index.vue` のコメントを修正

ページトップの「最終更新」に最も最近の更新時刻を表示・他

---

components/cards/MaskInventoryCard.vue

- #614 
- マップに注釈を追加
- ポップアップの表示内容を変更

マップに注釈を追加、ポップアップの表示内容を変更

---

components/cards/MaskInventoryCard.vue

- close #656 
- カード下部に埋め込み用ボタンを追加

ゲンキー店舗カードに埋め込み用ボタンを追加

---

components/cards/MaskInventoryCard.vue

- close #872 
- 福井県マスク在庫 が２つつかないように修正

余分なハッシュタグがつかないように修正

---

components/cards/MaskInventoryCard.vue

- close #899 
- 関連するツイートをblankで開くように変更した
~~## 📸 スクリーンショット / Screenshots~~

関連するツイートをblankで開くように変更

---

nuxt.config.ts
pages/cards/_card.vue

- close #985
- カード名ミスを修正
- 対象ページを生成するよう追加

入院患者数カードのページを表示できるよう修正

---

assets/global.scss
components/BreakingNews.vue

- close #1034 
- ボタンのCSSを修正して長くなる場合は改行表示するように修正

多言語化されると画面のレイアウトが崩れるバグを修正

---

components/DataTable.vue
components/cards/ConfirmedCasesAttributesCard.vue

- close #1129 
- 陽性患者の属性カードに注釈を追加した

陽性患者の属性カードに注釈を追加

---

components/BreakingNews.vue

- close #1335 
- 速報カードから緊急事態宣言へのリンクボタンを削除した

緊急事態宣言へのリンクボタンを削除

---

assets/locales/en.json

- close #1178
~## 📝 関連する issue / Related Issues~
- 日本語版の"注釈"にあたる翻訳を修正した
- 日本語
- 英語

"注釈"にあたる翻訳を修正

---

components/flow/FlowPcAdvisory.vue
components/flow/FlowSpAdvisory.vue

- close #2765
- フローページの問い合わせ先を変更

フローページの問い合わせ先を変更

---

components/DateSelectSlider.vue

- close #3077 
- スライダーとグラフの表示が正しくなるように修正

FIX: スライダーの表示期間が誤っている問題の修正

---

pages/index.vue

- close #4281
- トップページから検査実施人数カードを取下げ
- ページ自体は残っている&データもそのまま

disable InspectionPersonsNumberCard

---

components/DateSelectSlider.vue
components/TimeBarChart.vue
utils/formatGraph.ts

- close #5595 
- TimeBarChart のX軸２番目のラベル表示方法を修正
- グラフのラベルデータとして年も含むように修正
- ２番目のラベルは四半期ごとの表示に変更
- １番目のラベルは週ごとの表示に変更
- １番目のラベルが指すグラフを示すtickMarkを表示するように変更

TimeBarChart のサブX軸を正しく表示させる

---

utils/formatTable.ts

- close #6434
- formatTable.ts  が返す日付に西暦を追加

陽性患者の属性カードの日付に西暦を追加

---

components/flow/FlowPc.vue
components/flow/FlowPcAdvisory.vue
components/flow/FlowPcGeneral.vue
components/flow/FlowPcSpecific.vue
components/flow/FlowSpAdvisory.vue
components/flow/FlowSpBadCondition.vue
components/flow/FlowSpElder.vue
components/flow/FlowSpGeneral.vue
components/flow/flow_sp.scss
pages/flow.vue

- 受診・相談の目安を修正
- 県のサイトへのリンク先を変更
- close #6742 
- 受診・相談の目安となる内容を全面的に修正
- 該当の内容が記載された県のサイトへのリンクを修正
PC版のコンテンツ
スマートフォン版はWIP

「新型コロナウイルス感染症が心配なときに」の症状の見直し

---

components/ShopCount.vue
netlify.toml

- close #9132 
- APIを叩く部分を削除し、固定値(json)を詰めるようにする
- netlifyのredirect部分を削除
- /maskの導線は削除済み
- https://deploy-preview-9133--covid19-fukui.netlify.app/mask/
- /maskの画面で表示に問題なし

マスク提供店舗のツイート情報APIのクローズ
